campaign_select:
  type: container
  width: 1280
  height: 720
  anchor: center
  layer: Layers.UI

  children:
    # Title
    - type: label
      id: "title"
      text: "SELECT CAMPAIGN"
      width: 600
      height: 60
      anchor: top_center
      offset: [0, 100]
      font_size: 48
      color: [255, 255, 255]
      layer: Layers.UI

    # Campaign list container (dynamically populated)
    - type: container
      id: "campaign_list"
      width: 600
      height: 400
      anchor: "#title:bottom"
      align: top_center
      offset: [0, 60]
      layout: vertical
      spacing: 15
      layer: Layers.UI

    # Back button
    - type: button
      id: "back_button"
      text: "BACK"
      action: "back"
      width: 200
      height: 50
      anchor: bottom_center
      offset: [0, -80]
      color: [100, 100, 100]
      border: 2
      border_color: [140, 140, 140]
      border_radius: 8
      font_size: 24
      layer: Layers.UI