level_select:
  type: container
  size: [550, 730]
#  background: [20, 20, 30, 255]
  parent_anchor: center_left
  self_anchor: center_left
  offset: [0, 0]
  background:
    type: gradient
    direction: horizontal
    colors: [ [ 0, 0, 0, 200 ], [ 32, 32, 32, 0 ] ]
  border: 2
  border_color: [100, 100, 120, 0]
  border_radius: 10
  layer: Layers.UI

  children:
    # Title
    - type: label
      id: "title"
      text: "SELECT LEVEL"
      size: [600, 60]
      parent_anchor: top_left
      self_anchor: top_left
      offset: [-20, 80]
      font_size: 72
      color: [192, 192, 192]
      layer: Layers.UI

    # Level Button 1
    - type: button
      id: "level_btn_0"
      text: "Level 1"
      action: "select_level_0"
      size: [300, 70]
      parent_anchor: "#title:bottom_left"
      self_anchor: top_left
      offset: [100, 60]
      color: [96, 96, 96, 100]
      border: 2
      border_color: [100, 140, 220, 0]
      border_radius: 8
      font_size: 36
      layer: Layers.UI

    # Level Button 2
    - type: button
      id: "level_btn_1"
      text: "Level 2"
      action: "select_level_1"
      size: [300, 70]
      parent_anchor: "#level_btn_0:bottom"
      self_anchor: top_center
      offset: [0, 20]
      color: [96, 96, 96, 100]
      border: 2
      border_color: [100, 140, 220, 0]
      border_radius: 8
      font_size: 36
      layer: Layers.UI

    # Level Button 3
    - type: button
      id: "level_btn_2"
      text: "Level 3"
      action: "select_level_2"
      size: [300, 70]
      parent_anchor: "#level_btn_1:bottom"
      self_anchor: top_center
      offset: [0, 20]
      color: [96, 96, 96, 100]
      border: 2
      border_color: [100, 140, 0, 0]
      border_radius: 8
      font_size: 36
      layer: Layers.UI

    # Back button
    - type: button
      id: "btn_back"
      text: "BACK"
      action: "back"
      size: [150, 60]
      parent_anchor: "#level_btn_2:bottom_left"
      self_anchor: top_left
      offset: [0, 120]
      color: [96, 96, 96, 100]
      border: 2
      border_color: [150, 80, 80, 0]
      border_radius: 8
      font_size: 18
      layer: Layers.UI