  player_hud:
    type: container
    size: [1280, 720]
    parent_anchor: center
    self_anchor: center
    layer: Layers.UI
    children:

      - type: container
        id: "left_main_bar"
        size: [383, 36]
        parent_anchor: bottom_left
        self_anchor: bottom_left
        offset: [0, 0]
        image: "ui/bars/left_bar.png"

      - type: container
        id: "health_frame"
        size: [300, 78]
        parent_anchor: top_left
        self_anchor: top_left
        offset: [3, 4]
        image: "ui/bars/default_frame.png"

        children:

        - type: bar
          id: "health_bar"
          size: [260, 32]
          parent_anchor: "#health_frame:center"
          self_anchor: center
          offset: [8, 1]

          image: "ui/bars/health_bar.png"
          background: [0, 0, 0, 0]
          animated: true
          direction: horizontal

          bind: player.health_ratio
          max_value: 1.0
          min_value: 0.0


      - type: container
        id: "exp_frame"
        size: [ 300, 78 ]
        parent_anchor: top_right
        self_anchor: top_right
        offset: [ 3, 4 ]
        image: "ui/bars/default_frame.png"

        children:

          - type: bar
            id: "exp_bar"
            size: [ 260, 32 ]
            parent_anchor: "#exp_frame:center"
            self_anchor: center
            offset: [ 8, 1 ]

            image: "ui/bars/exp_bar.png"
            background: [ 0, 0, 0, 0 ]
            animated: true
            direction: horizontal

            bind: player.exp_ratio
            max_value: 1.0
            min_value: 0.0

      - type: container
        id: "right_main_bar"
        size: [383, 36]
        parent_anchor: bottom_right
        self_anchor: bottom_right
        offset: [0, 0]
        image: "ui/bars/right_bar.png"

        children:
        - type: container
          id: "stress_gauge"
          size: [150, 105]
          parent_anchor: bottom
          self_anchor: bottom
          offset: [0, 0]
          image: "ui/stress/stress_gauge.png"


        - type: needle
          id: "stress_needle"
          parent_anchor: bottom
          self_anchor: center
          offset: [0, -33]
          size: [200, 200]
          image: "ui/stress/stress_needle.png"

          bind: player.stress
          bind_max: player.stress_max

          min_value: 0
          min_angle: 80
          max_angle: -80