# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: build

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
      release_urls:
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame pyinstaller pyyaml
    - name: pyinstaller
      run: |
        pyinstaller --onefile --noconsole main.py

    - name: create a zip file (windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        tar -acf dist.zip ./dist

    - name: create a zip file (mac os)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        zip -r dist.zip ./dist

    - name: Upload artifact (windows)
      if: ${{ matrix.os == 'windows-latest' }}
      uses: actions/upload-artifact@v4
      with:
        name: windows_file
        path: dist/main.exe

    - name: Upload artifact (mac os)
      if: ${{ matrix.os == 'macos-latest' }}
      uses: actions/upload-artifact@v4
      with:
        name: mac_file
        path: dist/main.app

    - name: Upload release (windows)
      if: ${{ matrix.os == 'windows-latest' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ inputs.release_urls }}
        asset_path: ./dist.zip
        asset_name: main-windows-${{ inputs.tags }}.zip
        asset_content_type: application/zip

    - name: Upload release (mac os)
      if: ${{ matrix.os == 'macos-latest' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ inputs.release_urls }}
        asset_path: ./dist.zip
        asset_name: main-mac-${{ inputs.tags }}.zip
        asset_content_type: application/zip