name: check-pr-label

on:
  pull_request:
    branches:
      - main
    types: [labeled, unlabeled, opened, edited, reopened, synchronize, ready_for_review]

jobs:
  check-pr-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jefflinse/pr-semver-bump@v1.6.0
        name: validate pr label
        with:
          mode: validate
          repo-token: ${{ secrets.GITHUB_TOKEN }}